### ISSUE TITLE
Adds leading spacing to scroll view when using `.overlay`

### ISSUE THREAD

**Issue by mkaulfers** [gh123man/Refresher#14] opened 2023-10-05 20:10 UTC
As the title suggests, it adds this weird spacing to the leading edge of content in the scroll view. This is happening with the new `.scrollTargetBehavior` in `iOS 17+` See the screenshot. 

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-05 at 15 07 40](https://github.com/gh123man/SwiftUI-Refresher/assets/42121989/3c2d60ee-54e6-4ea9-8523-c32a15d5a496)

**Comment by gh123man** [comment] 2023-10-05 21:28
Hi, Thanks for the report. Could you provide a minimal reproducible example of the problem?

There is a sample app in this repo [with overlay mode being used here](https://github.com/gh123man/SwiftUI-Refresher/blob/master/Examples/ContentView.swift#L107) you could use as a template. 

I quickly tried a few combinations of `.scrollTargetBehavior` and could not reproduce the problem.

**Comment by gh123man** [comment] 2024-01-24 16:12
Closing this issue as I cannot reproduce it.

**Closed as completed by gh123man** 2024-01-24 16:12 UTC
